---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps-default
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./app/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: app
  validation: client

