apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: default
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: apps
  path: ./apps/staging
  prune: true
  validation: client
