---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: configmap
      sourceRef:
        kind: HelmRepository
        name: helm-private
      version: 0.1.0
  install: {}
  interval: 30s
  releaseName: prod
  targetNamespace: default
  values:
    home: Production
    infra:
      region: us-produciton
      zone: production-zone
    name: PRODUCTION
    projectCode: projectproduction

