---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stage
  namespace: flux-system
spec:
  chart:
    spec:
      chart: configmap
      sourceRef:
        kind: HelmRepository
        name: helm-private
      version: 0.1.0
  install: {}
  interval: 30s
  releaseName: stage
  targetNamespace: default
  values:
    home: STAGING
    infra:
      region: us-stating
      zone: stage-zone
    name: staging
    projectCode: stagingproject

