---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stage
  namespace: flux-system
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: helm-private
      version: 0.3.0
  install: {}
  interval: 30s
  releaseName: stage
  targetNamespace: default
  valuesFrom:
    - kind: ConfigMap
      name: stage-values
