apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - helm-release.yaml
configMapGenerator:
  - name: stage-values
    files:
      - values.yaml=stage-values.yaml
configurations:
  - kustomizeconfig.yaml
