---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stage2
  namespace: flux-system
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: helm-private
      version: 0.3.0
  install: {}
  interval: 30s
  releaseName: stage2
  targetNamespace: default
