apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myns
namePrefix: stage-
nameSuffix: "001"
bases:
  - ../application
resources:
  - namespace.yaml
patchesStrategicMerge:
  - replica_count.yaml
